#![allow(
    clippy::needless_raw_string_hashes,
    clippy::single_match_else,
    clippy::too_many_lines,
    clippy::writeln_empty_string
)]

use std::fmt::Write as _;

use crate::schema::{Schema, Type};

pub(crate) const fn header() -> &'static str {
    r#"#ifndef EXTERN_FILC_H
#define EXTERN_FILC_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    const uint8_t *ptr;
    size_t len;
} extern_filc_bytes;

typedef struct {
    const char *ptr;
    size_t len;
} extern_filc_string;

#endif
"#
}

pub(crate) fn generate(schema: &Schema, hash: &[u8; 32]) -> String {
    let mut output = String::new();
    writeln!(output, "/* @generated by filc-build; do not edit. */").unwrap();
    writeln!(output, "#include <errno.h>").unwrap();
    writeln!(output, "#include <stdbool.h>").unwrap();
    writeln!(output, "#include <stddef.h>").unwrap();
    writeln!(output, "#include <stdint.h>").unwrap();
    writeln!(output, "#include <stdio.h>").unwrap();
    writeln!(output, "#include <stdlib.h>").unwrap();
    writeln!(output, "#include <string.h>").unwrap();
    writeln!(output, "#include \"extern_filc.h\"").unwrap();
    writeln!(output, "#include \"{}\"", schema.bridge.header).unwrap();
    writeln!(output, "").unwrap();
    writeln!(output, "#define PROTOCOL_VERSION 2u").unwrap();
    writeln!(output, "#define REQUEST_KIND 1u").unwrap();
    writeln!(output, "#define RESPONSE_KIND 2u").unwrap();
    writeln!(output, "#define HEADER_LEN 20u").unwrap();
    writeln!(
        output,
        "#define MAX_FRAME_BYTES {}u",
        schema.bridge.max_frame_bytes
    )
    .unwrap();
    let hash_values = hash
        .iter()
        .map(|byte| format!("0x{byte:02x}"))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        output,
        "static const uint8_t SCHEMA_HASH[32] = {{{hash_values}}};"
    )
    .unwrap();
    output.push_str(PRELUDE);

    for handle in &schema.handles {
        writeln!(output, "").unwrap();
        writeln!(output, "typedef struct {{").unwrap();
        writeln!(output, "    uint64_t id;").unwrap();
        writeln!(output, "    {} value;", handle.c_type).unwrap();
        writeln!(output, "    bool live;").unwrap();
        writeln!(output, "}} handle_{}_slot;", handle.name).unwrap();
        writeln!(
            output,
            "static handle_{}_slot *handle_{}_slots;",
            handle.name, handle.name
        )
        .unwrap();
        writeln!(output, "static size_t handle_{}_length;", handle.name).unwrap();
        writeln!(output, "static size_t handle_{}_capacity;", handle.name).unwrap();
        writeln!(
            output,
            "static uint64_t handle_{}_next_id = 1u;",
            handle.name
        )
        .unwrap();
        writeln!(output, "").unwrap();
        writeln!(
            output,
            "static uint64_t handle_{}_insert({} value) {{",
            handle.name, handle.c_type
        )
        .unwrap();
        writeln!(
            output,
            "    if (value == NULL || handle_{}_next_id == 0u) return 0u;",
            handle.name
        )
        .unwrap();
        writeln!(output, "    size_t slot = handle_{}_length;", handle.name).unwrap();
        writeln!(
            output,
            "    for (size_t i = 0u; i < handle_{}_length; ++i) {{",
            handle.name
        )
        .unwrap();
        writeln!(
            output,
            "        if (!handle_{}_slots[i].live) {{ slot = i; break; }}",
            handle.name
        )
        .unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    if (slot == handle_{}_length) {{", handle.name).unwrap();
        writeln!(
            output,
            "        if (handle_{}_length == handle_{}_capacity) {{",
            handle.name, handle.name
        )
        .unwrap();
        writeln!(
            output,
            "            size_t next = handle_{}_capacity == 0u ? 8u : handle_{}_capacity * 2u;",
            handle.name, handle.name
        )
        .unwrap();
        writeln!(output, "            if (next < handle_{}_capacity || next > SIZE_MAX / sizeof(*handle_{}_slots)) return 0u;", handle.name, handle.name).unwrap();
        writeln!(
            output,
            "            void *grown = realloc(handle_{}_slots, next * sizeof(*handle_{}_slots));",
            handle.name, handle.name
        )
        .unwrap();
        writeln!(output, "            if (grown == NULL) return 0u;").unwrap();
        writeln!(output, "            handle_{}_slots = grown;", handle.name).unwrap();
        writeln!(
            output,
            "            handle_{}_capacity = next;",
            handle.name
        )
        .unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "        ++handle_{}_length;", handle.name).unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(
            output,
            "    uint64_t id = handle_{}_next_id++;",
            handle.name
        )
        .unwrap();
        writeln!(output, "    handle_{}_slots[slot] = (handle_{}_slot){{.id = id, .value = value, .live = true}};", handle.name, handle.name).unwrap();
        writeln!(output, "    return id;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output, "").unwrap();
        writeln!(
            output,
            "static {} handle_{}_lookup(uint64_t id) {{",
            handle.c_type, handle.name
        )
        .unwrap();
        writeln!(
            output,
            "    for (size_t i = 0u; i < handle_{}_length; ++i) {{",
            handle.name
        )
        .unwrap();
        writeln!(output, "        if (handle_{}_slots[i].live && handle_{}_slots[i].id == id) return handle_{}_slots[i].value;", handle.name, handle.name, handle.name).unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    return NULL;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output, "").unwrap();
        writeln!(
            output,
            "static bool decoder_handle_{}(Decoder *decoder, {} *value) {{",
            handle.name, handle.c_type
        )
        .unwrap();
        writeln!(output, "    uint64_t id = 0u;").unwrap();
        writeln!(output, "    if (!decoder_u64(decoder, &id)) return false;").unwrap();
        writeln!(output, "    *value = handle_{}_lookup(id);", handle.name).unwrap();
        writeln!(output, "    return *value != NULL;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output, "").unwrap();
        writeln!(
            output,
            "static bool handle_{}_remove(uint64_t id) {{",
            handle.name
        )
        .unwrap();
        writeln!(
            output,
            "    for (size_t i = 0u; i < handle_{}_length; ++i) {{",
            handle.name
        )
        .unwrap();
        writeln!(
            output,
            "        if (handle_{}_slots[i].live && handle_{}_slots[i].id == id) {{",
            handle.name, handle.name
        )
        .unwrap();
        if let Some(drop) = &handle.drop {
            writeln!(
                output,
                "            {}(handle_{}_slots[i].value);",
                drop.symbol, handle.name
            )
            .unwrap();
        }
        writeln!(
            output,
            "            handle_{}_slots[i].live = false;",
            handle.name
        )
        .unwrap();
        writeln!(output, "            return true;").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    return false;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output, "").unwrap();
        writeln!(
            output,
            "static void handle_{}_remove_all(void) {{",
            handle.name
        )
        .unwrap();
        writeln!(
            output,
            "    for (size_t i = 0u; i < handle_{}_length; ++i) {{",
            handle.name
        )
        .unwrap();
        if let Some(drop) = &handle.drop {
            writeln!(
                output,
                "        if (handle_{}_slots[i].live) {}(handle_{}_slots[i].value);",
                handle.name, drop.symbol, handle.name
            )
            .unwrap();
        }
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    free(handle_{}_slots);", handle.name).unwrap();
        writeln!(output, "    handle_{}_slots = NULL;", handle.name).unwrap();
        writeln!(output, "    handle_{}_length = 0u;", handle.name).unwrap();
        writeln!(output, "    handle_{}_capacity = 0u;", handle.name).unwrap();
        writeln!(output, "}}").unwrap();
    }

    output.push_str(
        "\nstatic bool dispatch(const uint8_t *payload, size_t payload_len, Buffer *response) {\n",
    );
    output.push_str("    Decoder request = {.data = payload, .len = payload_len, .cursor = 0u};\n");
    output.push_str("    const uint8_t *hash = decoder_take(&request, 32u);\n");
    output.push_str("    uint32_t operation = 0u;\n");
    output.push_str("    if (hash == NULL || memcmp(hash, SCHEMA_HASH, 32u) != 0) return buffer_error(response, \"schema mismatch\");\n");
    output.push_str("    if (!decoder_u32(&request, &operation)) return buffer_error(response, \"missing operation\");\n");
    output.push_str("    switch (operation) {\n");

    for (index, function) in schema.functions.iter().enumerate() {
        let operation = u32::try_from(index + 1).expect("function count fits u32");
        writeln!(output, "    case {operation}u: {{").unwrap();
        for param in &function.params {
            let ty = Type::parse(&param.ty).expect("validated type");
            writeln!(
                output,
                "        {} {} = {};",
                c_type(schema, &ty),
                param.name,
                c_zero(&ty)
            )
            .unwrap();
            writeln!(
                output,
                "        if (!{}) return buffer_error(response, \"invalid argument {}\");",
                c_decode(&ty, &param.name),
                param.name
            )
            .unwrap();
        }
        output.push_str("        if (request.cursor != request.len) return buffer_error(response, \"trailing argument bytes\");\n");
        let arguments = function
            .params
            .iter()
            .map(|param| param.name.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        let result = Type::parse(&function.result.ty).expect("validated type");
        match &result {
            Type::Void => {
                writeln!(output, "        {}({arguments});", function.symbol).unwrap();
            }
            _ => {
                writeln!(
                    output,
                    "        {} result = {}({arguments});",
                    c_type(schema, &result),
                    function.symbol
                )
                .unwrap();
                match &result {
                    Type::Handle(name) => {
                        writeln!(
                            output,
                            "        uint64_t id = handle_{name}_insert(result);"
                        )
                        .unwrap();
                        if let Some(drop) = &schema.handle(name).drop {
                            writeln!(output, "        if (id == 0u) {{ {}(result); return buffer_error(response, \"could not retain opaque handle\"); }}", drop.symbol).unwrap();
                        } else {
                            output.push_str("        if (id == 0u) return buffer_error(response, \"could not retain opaque handle\");\n");
                        }
                        output.push_str("        if (!buffer_u64(response, id)) return buffer_error(response, \"result exceeds maximum frame size\");\n");
                    }
                    Type::String => {
                        output
                            .push_str("        bool encoded = buffer_string(response, result);\n");
                        if let Some(free) = &function.result.free {
                            writeln!(output, "        {free}(result.ptr);").unwrap();
                        }
                        output.push_str("        if (!encoded) return buffer_error(response, \"result exceeds maximum frame size\");\n");
                    }
                    Type::Bytes => {
                        output.push_str(
                            "        bool encoded = buffer_bytes_view(response, result);\n",
                        );
                        if let Some(free) = &function.result.free {
                            writeln!(output, "        {free}(result.ptr);").unwrap();
                        }
                        output.push_str("        if (!encoded) return buffer_error(response, \"result exceeds maximum frame size\");\n");
                    }
                    _ => {
                        writeln!(
                            output,
                            "        if (!buffer_{}(response, result)) return buffer_error(response, \"result exceeds maximum frame size\");",
                            result.codec_method()
                        )
                        .unwrap();
                    }
                }
            }
        }
        output.push_str("        return true;\n");
        output.push_str("    }\n");
    }

    for (index, handle) in schema.handles.iter().enumerate() {
        if handle.drop.is_none() {
            continue;
        }
        let operation = 0x8000_0000_u32 + u32::try_from(index).expect("handle count fits u32");
        writeln!(output, "    case {operation}u: {{").unwrap();
        output.push_str("        uint64_t id = 0u;\n");
        output.push_str("        if (!decoder_u64(&request, &id) || request.cursor != request.len) return buffer_error(response, \"invalid handle release\");\n");
        writeln!(output, "        if (!handle_{}_remove(id)) return buffer_error(response, \"unknown opaque handle\");", handle.name).unwrap();
        output.push_str("        return true;\n");
        output.push_str("    }\n");
    }

    output.push_str("    default:\n");
    output.push_str("        return buffer_error(response, \"unknown operation\");\n");
    output.push_str("    }\n");
    output.push_str("}\n");
    output.push_str(MAIN);
    output.push_str("\nstatic void release_all_handles(void) {\n");
    for handle in &schema.handles {
        writeln!(output, "    handle_{}_remove_all();", handle.name).unwrap();
    }
    output.push_str("}\n");
    output
}

fn c_type(schema: &Schema, ty: &Type) -> String {
    match ty {
        Type::Bool => "bool".into(),
        Type::I32 => "int32_t".into(),
        Type::U32 => "uint32_t".into(),
        Type::I64 => "int64_t".into(),
        Type::U64 => "uint64_t".into(),
        Type::F32 => "float".into(),
        Type::F64 => "double".into(),
        Type::String => "extern_filc_string".into(),
        Type::Bytes => "extern_filc_bytes".into(),
        Type::Handle(name) => schema.handle(name).c_type.clone(),
        Type::Void => "void".into(),
    }
}

fn c_zero(ty: &Type) -> &'static str {
    match ty {
        Type::Bool => "false",
        Type::F32 | Type::F64 => "0.0",
        Type::String | Type::Bytes => "{0}",
        Type::Handle(_) => "NULL",
        Type::I32 | Type::U32 | Type::I64 | Type::U64 => "0",
        Type::Void => "",
    }
}

fn c_decode(ty: &Type, name: &str) -> String {
    match ty {
        Type::Handle(handle) => format!("decoder_handle_{handle}(&request, &{name})"),
        _ => format!("decoder_{}(&request, &{name})", ty.codec_method()),
    }
}

const PRELUDE: &str = r#"

typedef struct {
    uint8_t *data;
    size_t len;
    size_t capacity;
} Buffer;

typedef struct {
    const uint8_t *data;
    size_t len;
    size_t cursor;
} Decoder;

static bool buffer_reserve(Buffer *buffer, size_t additional) {
    if (additional > MAX_FRAME_BYTES || buffer->len > MAX_FRAME_BYTES - additional) return false;
    size_t needed = buffer->len + additional;
    if (needed <= buffer->capacity) return true;
    size_t capacity = buffer->capacity == 0u ? 64u : buffer->capacity;
    while (capacity < needed) {
        if (capacity > MAX_FRAME_BYTES / 2u) {
            capacity = MAX_FRAME_BYTES;
            break;
        }
        capacity *= 2u;
    }
    void *grown = realloc(buffer->data, capacity);
    if (grown == NULL) return false;
    buffer->data = grown;
    buffer->capacity = capacity;
    return true;
}

static bool buffer_append(Buffer *buffer, const void *data, size_t length) {
    if (!buffer_reserve(buffer, length)) return false;
    if (length != 0u) memcpy(buffer->data + buffer->len, data, length);
    buffer->len += length;
    return true;
}

static bool buffer_u8(Buffer *buffer, uint8_t value) {
    return buffer_append(buffer, &value, 1u);
}

static bool buffer_u32(Buffer *buffer, uint32_t value) {
    uint8_t bytes[4];
    for (size_t i = 0u; i < 4u; ++i) bytes[i] = (uint8_t)(value >> (i * 8u));
    return buffer_append(buffer, bytes, sizeof(bytes));
}

static bool buffer_i32(Buffer *buffer, int32_t value) { return buffer_u32(buffer, (uint32_t)value); }

static bool buffer_u64(Buffer *buffer, uint64_t value) {
    uint8_t bytes[8];
    for (size_t i = 0u; i < 8u; ++i) bytes[i] = (uint8_t)(value >> (i * 8u));
    return buffer_append(buffer, bytes, sizeof(bytes));
}

static bool buffer_i64(Buffer *buffer, int64_t value) { return buffer_u64(buffer, (uint64_t)value); }
static bool buffer_bool(Buffer *buffer, bool value) { return buffer_u8(buffer, value ? 1u : 0u); }

static bool buffer_f32(Buffer *buffer, float value) {
    uint32_t bits = 0u;
    memcpy(&bits, &value, sizeof(bits));
    return buffer_u32(buffer, bits);
}

static bool buffer_f64(Buffer *buffer, double value) {
    uint64_t bits = 0u;
    memcpy(&bits, &value, sizeof(bits));
    return buffer_u64(buffer, bits);
}

static bool buffer_bytes(Buffer *buffer, const uint8_t *data, size_t length) {
    if (length > UINT32_MAX) return false;
    return buffer_u32(buffer, (uint32_t)length) && buffer_append(buffer, data, length);
}

static bool buffer_bytes_view(Buffer *buffer, extern_filc_bytes value) {
    return (value.ptr != NULL || value.len == 0u) && buffer_bytes(buffer, value.ptr, value.len);
}

static bool buffer_string(Buffer *buffer, extern_filc_string value) {
    return (value.ptr != NULL || value.len == 0u) && buffer_bytes(buffer, (const uint8_t *)value.ptr, value.len);
}

static bool buffer_error(Buffer *buffer, const char *message) {
    buffer->len = 0u;
    return buffer_append(buffer, message, strlen(message)) && false;
}

static const uint8_t *decoder_take(Decoder *decoder, size_t length) {
    if (length > decoder->len || decoder->cursor > decoder->len - length) return NULL;
    const uint8_t *value = decoder->data + decoder->cursor;
    decoder->cursor += length;
    return value;
}

static bool decoder_u8(Decoder *decoder, uint8_t *value) {
    const uint8_t *bytes = decoder_take(decoder, 1u);
    if (bytes == NULL) return false;
    *value = bytes[0];
    return true;
}

static bool decoder_bool(Decoder *decoder, bool *value) {
    uint8_t wire = 0u;
    if (!decoder_u8(decoder, &wire) || wire > 1u) return false;
    *value = wire != 0u;
    return true;
}

static bool decoder_u32(Decoder *decoder, uint32_t *value) {
    const uint8_t *bytes = decoder_take(decoder, 4u);
    if (bytes == NULL) return false;
    *value = 0u;
    for (size_t i = 0u; i < 4u; ++i) *value |= (uint32_t)bytes[i] << (i * 8u);
    return true;
}

static bool decoder_i32(Decoder *decoder, int32_t *value) {
    uint32_t wire = 0u;
    if (!decoder_u32(decoder, &wire)) return false;
    memcpy(value, &wire, sizeof(wire));
    return true;
}

static bool decoder_u64(Decoder *decoder, uint64_t *value) {
    const uint8_t *bytes = decoder_take(decoder, 8u);
    if (bytes == NULL) return false;
    *value = 0u;
    for (size_t i = 0u; i < 8u; ++i) *value |= (uint64_t)bytes[i] << (i * 8u);
    return true;
}

static bool decoder_i64(Decoder *decoder, int64_t *value) {
    uint64_t wire = 0u;
    if (!decoder_u64(decoder, &wire)) return false;
    memcpy(value, &wire, sizeof(wire));
    return true;
}

static bool decoder_f32(Decoder *decoder, float *value) {
    uint32_t bits = 0u;
    if (!decoder_u32(decoder, &bits)) return false;
    memcpy(value, &bits, sizeof(bits));
    return true;
}

static bool decoder_f64(Decoder *decoder, double *value) {
    uint64_t bits = 0u;
    if (!decoder_u64(decoder, &bits)) return false;
    memcpy(value, &bits, sizeof(bits));
    return true;
}

static bool decoder_bytes(Decoder *decoder, extern_filc_bytes *value) {
    uint32_t length = 0u;
    if (!decoder_u32(decoder, &length)) return false;
    const uint8_t *bytes = decoder_take(decoder, length);
    if (bytes == NULL) return false;
    *value = (extern_filc_bytes){.ptr = bytes, .len = length};
    return true;
}

static bool decoder_string(Decoder *decoder, extern_filc_string *value) {
    extern_filc_bytes bytes = {0};
    if (!decoder_bytes(decoder, &bytes)) return false;
    *value = (extern_filc_string){.ptr = (const char *)bytes.ptr, .len = bytes.len};
    return true;
}
"#;

const MAIN: &str = r#"

static int read_exact(uint8_t *destination, size_t length, bool permit_clean_eof) {
    size_t offset = 0u;
    while (offset < length) {
        size_t count = fread(destination + offset, 1u, length - offset, stdin);
        if (count != 0u) {
            offset += count;
            continue;
        }
        if (feof(stdin)) return permit_clean_eof && offset == 0u ? 0 : -1;
        if (ferror(stdin) && errno == EINTR) {
            clearerr(stdin);
            continue;
        }
        return -1;
    }
    return 1;
}

static bool write_exact(const uint8_t *source, size_t length) {
    size_t offset = 0u;
    while (offset < length) {
        size_t count = fwrite(source + offset, 1u, length - offset, stdout);
        if (count != 0u) {
            offset += count;
            continue;
        }
        if (ferror(stdout) && errno == EINTR) {
            clearerr(stdout);
            continue;
        }
        return false;
    }
    return true;
}

static uint16_t load_u16(const uint8_t *bytes) {
    return (uint16_t)bytes[0] | (uint16_t)((uint16_t)bytes[1] << 8u);
}

static uint32_t load_u32(const uint8_t *bytes) {
    uint32_t value = 0u;
    for (size_t i = 0u; i < 4u; ++i) value |= (uint32_t)bytes[i] << (i * 8u);
    return value;
}

static uint64_t load_u64(const uint8_t *bytes) {
    uint64_t value = 0u;
    for (size_t i = 0u; i < 8u; ++i) value |= (uint64_t)bytes[i] << (i * 8u);
    return value;
}

static void store_u16(uint8_t *bytes, uint16_t value) {
    for (size_t i = 0u; i < 2u; ++i) bytes[i] = (uint8_t)(value >> (i * 8u));
}

static void store_u32(uint8_t *bytes, uint32_t value) {
    for (size_t i = 0u; i < 4u; ++i) bytes[i] = (uint8_t)(value >> (i * 8u));
}

static void store_u64(uint8_t *bytes, uint64_t value) {
    for (size_t i = 0u; i < 8u; ++i) bytes[i] = (uint8_t)(value >> (i * 8u));
}

static bool send_response(uint64_t request_id, uint8_t status, const Buffer *response) {
    if (response->len > UINT32_MAX) return false;
    uint8_t header[HEADER_LEN] = {0};
    memcpy(header, "FILC", 4u);
    store_u16(header + 4u, PROTOCOL_VERSION);
    header[6] = RESPONSE_KIND;
    header[7] = status;
    store_u64(header + 8u, request_id);
    store_u32(header + 16u, (uint32_t)response->len);
    return write_exact(header, sizeof(header))
        && write_exact(response->data, response->len)
        && fflush(stdout) == 0;
}

static void release_all_handles(void);

int main(void) {
    int exit_code = 0;
    for (;;) {
        uint8_t header[HEADER_LEN] = {0};
        int header_result = read_exact(header, sizeof(header), true);
        if (header_result == 0) break;
        if (header_result < 0
            || memcmp(header, "FILC", 4u) != 0
            || load_u16(header + 4u) != PROTOCOL_VERSION
            || header[6] != REQUEST_KIND
            || header[7] != 0u) {
            exit_code = 2;
            break;
        }
        uint64_t request_id = load_u64(header + 8u);
        uint32_t payload_len = load_u32(header + 16u);
        if (payload_len > MAX_FRAME_BYTES) {
            exit_code = 2;
            break;
        }
        uint8_t *payload = payload_len == 0u ? NULL : malloc(payload_len);
        if (payload_len != 0u && payload == NULL) {
            exit_code = 3;
            break;
        }
        if (read_exact(payload, payload_len, false) < 0) {
            free(payload);
            exit_code = 2;
            break;
        }
        Buffer response = {0};
        bool success = dispatch(payload, payload_len, &response);
        free(payload);
        if (!send_response(request_id, success ? 0u : 1u, &response)) {
            free(response.data);
            exit_code = 2;
            break;
        }
        free(response.data);
    }
    release_all_handles();
    return exit_code;
}
"#;
