#![allow(clippy::too_many_lines, clippy::writeln_empty_string)]

use std::fmt::Write as _;

use crate::schema::{Schema, Type, shouty};

fn rust_u32(value: u32) -> String {
    let digits = value.to_string();
    let mut separated = String::with_capacity(digits.len() + digits.len() / 3);
    for (index, digit) in digits.chars().enumerate() {
        if index > 0 && (digits.len() - index) % 3 == 0 {
            separated.push('_');
        }
        separated.push(digit);
    }
    separated
}

pub(crate) fn generate(schema: &Schema, hash: &[u8; 32]) -> String {
    let mut output = String::new();
    let env_name = format!("EXTERN_FILC_{}_PROGRAM", shouty(&schema.bridge.name));
    let hash_values = hash
        .iter()
        .map(u8::to_string)
        .collect::<Vec<_>>()
        .join(", ");

    writeln!(output, "// @generated by filc-build; do not edit.").unwrap();
    writeln!(output, "const SCHEMA_HASH: [u8; 32] = [{hash_values}];").unwrap();
    writeln!(
        output,
        "const MAX_FRAME_BYTES: u32 = {};",
        rust_u32(schema.bridge.max_frame_bytes)
    )
    .unwrap();
    writeln!(
        output,
        "const DEFAULT_PROGRAM: &str = env!(\"{env_name}\");"
    )
    .unwrap();
    writeln!(
        output,
        "static BRIDGE: filc::Bridge = filc::Bridge::new(\"{env_name}\", DEFAULT_PROGRAM, MAX_FRAME_BYTES);"
    )
    .unwrap();

    for (index, function) in schema.functions.iter().enumerate() {
        let operation = rust_u32(u32::try_from(index + 1).expect("function count fits u32"));
        let params = function
            .params
            .iter()
            .map(|param| {
                let ty = Type::parse(&param.ty).expect("validated type");
                match ty {
                    Type::Handle(ref name) => {
                        format!("{}: &{}", param.name, schema.handle(name).rust_name)
                    }
                    _ => format!("{}: {}", param.name, ty.rust_argument()),
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        let result = Type::parse(&function.result.ty).expect("validated type");
        let rust_result = match &result {
            Type::Handle(name) => schema.handle(name).rust_name.clone(),
            _ => result.rust_result().to_owned(),
        };
        let visibility = if function.visibility.is_empty() {
            String::new()
        } else {
            format!("{} ", function.visibility)
        };
        writeln!(output, "").unwrap();
        writeln!(
            output,
            "/// Calls `{}` inside the process-isolated Fil-C helper.",
            function.symbol
        )
        .unwrap();
        writeln!(
            output,
            "{visibility}fn {}({params}) -> filc::Result<{rust_result}> {{",
            function.name
        )
        .unwrap();
        writeln!(output, "    let connection = BRIDGE.connection()?;").unwrap();
        writeln!(output, "    let mut arguments = filc::Encoder::new();").unwrap();
        for param in &function.params {
            let ty = Type::parse(&param.ty).expect("validated type");
            match ty {
                Type::String | Type::Bytes => writeln!(
                    output,
                    "    arguments.{}({})?;",
                    ty.codec_method(),
                    param.name
                )
                .unwrap(),
                Type::Handle(_) => writeln!(
                    output,
                    "    arguments.u64({}.id_for(&connection)?);",
                    param.name
                )
                .unwrap(),
                Type::Void => unreachable!("validated parameter"),
                _ => writeln!(
                    output,
                    "    arguments.{}({});",
                    ty.codec_method(),
                    param.name
                )
                .unwrap(),
            }
        }
        writeln!(
            output,
            "    let response = BRIDGE.call(&connection, SCHEMA_HASH, {operation}, &arguments.finish())?;"
        )
        .unwrap();
        writeln!(
            output,
            "    let mut result = filc::Decoder::new(&response);"
        )
        .unwrap();
        match result {
            Type::Void => {
                writeln!(output, "    result.finish()?;").unwrap();
                writeln!(output, "    Ok(())").unwrap();
            }
            Type::Handle(ref name) => {
                writeln!(output, "    let id = result.u64()?;").unwrap();
                writeln!(output, "    result.finish()?;").unwrap();
                writeln!(
                    output,
                    "    Ok({} {{ id: Some(id), connection }})",
                    schema.handle(name).rust_name
                )
                .unwrap();
            }
            _ => {
                writeln!(
                    output,
                    "    let value = result.{}()?;",
                    result.codec_method()
                )
                .unwrap();
                writeln!(output, "    result.finish()?;").unwrap();
                writeln!(output, "    Ok(value)").unwrap();
            }
        }
        writeln!(output, "}}").unwrap();
    }

    for (index, handle) in schema.handles.iter().enumerate() {
        let handle_type = &handle.rust_name;
        let visibility = handle_visibility(schema, &handle.name);
        let visibility = if visibility.is_empty() {
            String::new()
        } else {
            format!("{visibility} ")
        };
        let drop_operation = 0x8000_0000_u32 + u32::try_from(index).expect("handle count fits u32");
        let drop_operation = rust_u32(drop_operation);
        writeln!(output, "").unwrap();
        writeln!(
            output,
            "/// An opaque value owned by the process-isolated Fil-C helper."
        )
        .unwrap();
        writeln!(output, "#[derive(Debug)]").unwrap();
        writeln!(output, "{visibility}struct {handle_type} {{").unwrap();
        writeln!(output, "    id: Option<u64>,").unwrap();
        writeln!(output, "    connection: std::sync::Arc<filc::Connection>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output, "").unwrap();
        writeln!(output, "impl {handle_type} {{").unwrap();
        writeln!(
            output,
            "    fn id_for(&self, connection: &std::sync::Arc<filc::Connection>) -> filc::Result<u64> {{"
        )
        .unwrap();
        writeln!(
            output,
            "        if std::sync::Arc::ptr_eq(&self.connection, connection) {{"
        )
        .unwrap();
        writeln!(
            output,
            "            self.id.ok_or(filc::Error::ReleasedHandle)"
        )
        .unwrap();
        writeln!(output, "        }} else {{").unwrap();
        writeln!(output, "            Err(filc::Error::WrongConnection)").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        if handle.drop.is_some() {
            writeln!(output, "").unwrap();
            writeln!(output, "    fn release(&mut self) -> filc::Result<()> {{").unwrap();
            writeln!(
                output,
                "        let Some(id) = self.id.take() else {{ return Ok(()); }};"
            )
            .unwrap();
            writeln!(output, "        let mut arguments = filc::Encoder::new();").unwrap();
            writeln!(output, "        arguments.u64(id);").unwrap();
            writeln!(
                output,
                "        self.connection.call(SCHEMA_HASH, {drop_operation}, &arguments.finish())?;"
            )
            .unwrap();
            writeln!(output, "        Ok(())").unwrap();
            writeln!(output, "    }}").unwrap();
        }
        writeln!(output, "}}").unwrap();
        if let Some(drop) = &handle.drop {
            writeln!(output, "").unwrap();
            writeln!(output, "impl Drop for {handle_type} {{").unwrap();
            writeln!(output, "    fn drop(&mut self) {{").unwrap();
            writeln!(output, "        let _ = self.release();").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output, "}}").unwrap();
            let visibility = if drop.visibility.is_empty() {
                String::new()
            } else {
                format!("{} ", drop.visibility)
            };
            writeln!(output, "").unwrap();
            writeln!(output, "/// Explicitly releases this Fil-C-owned handle.").unwrap();
            writeln!(
                output,
                "{visibility}fn {}(mut handle: {handle_type}) -> filc::Result<()> {{",
                drop.name
            )
            .unwrap();
            writeln!(output, "    handle.release()").unwrap();
            writeln!(output, "}}").unwrap();
        }
    }
    output
}

fn handle_visibility(schema: &Schema, handle: &str) -> String {
    let wire_type = format!("handle:{handle}");
    schema
        .functions
        .iter()
        .find(|function| function.result.ty == wire_type)
        .map_or_else(String::new, |function| function.visibility.clone())
}

#[cfg(test)]
mod tests {
    use super::generate;
    use crate::schema::Schema;

    #[test]
    fn generates_fallible_free_functions_and_lazy_handles() {
        let schema = Schema::parse(
            r#"
            #[filc::bridge(name = "demo", header = "demo.h", sources = ["demo.c"])]
            unsafe extern "Fil-C" {
                pub fn add(left: i32, right: i32) -> i32;
                pub fn counter_new(initial: i64) -> *mut counter_t;
                #[filc::drop]
                pub fn counter_drop(counter: *mut counter_t);
            }
            "#,
        )
        .unwrap();
        let generated = generate(&schema, &[7; 32]);
        assert!(generated.contains("pub fn add(left: i32, right: i32) -> filc::Result<i32>"));
        assert!(generated.contains("static BRIDGE: filc::Bridge"));
        assert!(generated.contains("pub struct CounterT"));
        assert!(generated.contains("pub fn counter_drop(mut handle: CounterT)"));
        assert!(!generated.contains("fn spawn"));

        let without_drop = Schema::parse(
            r#"
            #[filc::bridge(name = "demo", header = "demo.h", sources = ["demo.c"])]
            unsafe extern "Fil-C" {
                pub fn counter_new(initial: i64) -> *mut counter_t;
            }
            "#,
        )
        .unwrap();
        let generated = generate(&without_drop, &[9; 32]);
        assert!(generated.contains("pub struct CounterT"));
        assert!(!generated.contains("impl Drop for CounterT"));
    }
}
